blank_issues_enabled: false
contact_links:
  - name: "Have implementation questions?"
    url: "https://github.com/notabeen/notabeen-ai-email-assistant#readme"
    about: "Check the README for support options and additional documentation."
